baseURL = 'https://wordle.tomhummel.com/'
languageCode = 'en-us'
title = "Tom Hummel's Wordle Data"
enableGitInfo = true

[params]
    github_repo = "https://github.com/tphummel/wordle/"

[taxonomies]
    tag = 'tags'
    word = 'words'

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
