baseURL = 'https://wordle.tomhummel.com/'
languageCode = 'en-us'
title = "Tom Hummel's Wordle Data"
enableGitInfo = true
timeZone = 'America/Los_Angeles'
enableInlineShortcodes = true

[params]
    github_repo = "https://github.com/tphummel/wordle/"

[taxonomies]
    tag = 'tags'
    word = 'words'
    puzzle = 'puzzles'
    contest = 'contests'
    hash = 'hashes'
    openerhash = 'openerhashes'
    shift = 'shifts'
    opener = 'openers'
    middler = 'middlers'

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[outputFormats]
  [outputFormats.p8s]
    baseName = 'metrics'
    suffix = 'txt'
    isPlainText = true
    mediaType = 'text/plain'

[outputs]
  home = ['html', 'p8s']